### ISSUE TITLE
issue with new version

### ISSUE THREAD

**Issue by tkcaccia** [workflowr/workflowr#291]
I report this warnings with the loading of the library

Error: package or namespace load failed for ‘workflowr’ in dyn.load(file, DLLpath = DLLpath, ...):
 function 'execLaterFdNative' not provided by package 'later'

**Comment by jdblischak** [comment]
@tkcaccia thanks for your report. There appears to be a problem with the recently released {later} that was submitted to CRAN yesterday.

xref: https://github.com/r-lib/later/issues/203

Could you please try re-installing {later}, {promises}, and {httpuv}?

```sh
install.packages(c("later", "promises", "httpuv"))
library("workflowr")
```

**Comment by jcheng5** [comment]
I'm so sorry 😭  But yes, upgrading later should fix it

**Comment by jdblischak** [comment]
@jcheng5 No worries. Thanks for the quick diagnosis!

@tkcaccia Please let us know if upgrading {later} does not solve your problem
